music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'


urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'), 
    # /music/albums/
    url(r'^albums/$', views.IndexView.as_view(), name='index'),	
    # /register/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    #/music/albums/'$pk'/
    url(r'^albums/(?P<pk>[0-9]+)/$', views.AlbumDetailView.as_view(), name='detail'),
    #/music/albums/add/
    url(r'^albums/add/$', views.AlbumCreate.as_view(), name='album-add'),
    #/music/albums/'$pk'
    url(r'^albums/(?P<pk>[0-9]+)/update/$', views.AlbumUpdate.as_view(), name='album-update'),
    #/music/albums/'$pk'/delete
    url(r'^albums/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
    #/music/songs
    url(r'^songs/', views.SongView.as_view(), name='songs'),
    #/music/songs/add/
    url(r'^songs/add/$', views.SongCreate.as_view(), name='song-add'),
    #/music/songs/'$pk'/delete
    url(r'^songs/(?P<pk>[0-9]+)/delete/$', views.SongDelete.as_view(), name='song-delete'),
    #/login/
    url(r'^login/$', views.user_login, name='login'),
    #/logout/
    url(r'^logout/$', views.user_logout, name='logout'),
    #/friends/
    url(r'^friends/$', views.FriendView.as_view(), name='list-friends'),
    #/friends/'$pk'/delete
    url(r'^friends/(?P<pk>[0-9]+)/delete/$', views.friend_remove, name='friend-remove'),
    #/friends/reqs/'$pk'/answer
    url(r'^friends/reqs/accept/(?P<pk>[0-9]+)/$',  views.accept_friend_req, name='accept-friend-req'),
    #/friends/reqs/'$pk'/answer
    url(r'^friends/reqs/decline/(?P<pk>[0-9]+)/$',  views.decline_friend_req, name='decline-friend-req'),
    #/friends/reqs
    url(r'^friends/reqs/$',  views.FriendshipReqView.as_view(), name='friend-reqs'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.urlresolvers import reverse


class Album(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()  # s3

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + " - " + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    song_url = models.CharField(max_length=1000, default="")
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title


class FriendshipStatus(models.Model):
    from_user = models.ForeignKey(User, related_name='friendship_requests_sent')
    to_user = models.ForeignKey(User, related_name='friendship_requests_received')
    friendship_status = models.CharField(max_length=50, default="not_friends")

    def __str__(self):
        if self.friendship_status == "pending":
            return "User #%s has requested friendship to #%s" % (self.from_user.id, self.to_user.id)
        elif self.friendship_status == "friends":
            return "User #%s and #%s are friends" % (self.from_user.id, self.to_user.id)
        else:
            return "User #%s and #%s are not friends" % (self.from_user.id, self.to_user.id)

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.contrib.auth.models import User
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Album, Song, FriendshipStatus
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .forms import UserForm


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class SongView(generic.ListView):
    template_name = 'music/songs.html'
    context_object_name = 'songs'

    def get_queryset(self):
        qs = Song.objects.all()
        try:
            if self.request.GET['q'] is not None:
                qs = qs.filter(song_title__icontains=self.request.GET['q'])
            return qs
        except:
            return qs


class AlbumDetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class SongCreate(CreateView):
    model = Song
    fields = ['album', 'song_title', 'song_url']
    success_url = reverse_lazy('music:index')


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class SongDelete(DeleteView):
    model = Song
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')
        return render(request, self.template_name, {'form': form})


def user_logout(request):
    logout(request)
    return redirect('music:index')


def user_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('music:index')
            else:
                return render(request, 'music/login_form.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/login_form.html', {'error_message': 'Invalid login, try again!'})
    return render(request, 'music/login_form.html')


class FriendView(generic.ListView):
    template_name = 'music/friends.html'
    context_object_name = 'all_friends'

    def get_queryset(self):
        return FriendshipStatus.objects.all().filter(to_user=self.request.user, friendship_status="friends")


class FriendshipReqView(generic.ListView):
    template_name = 'music/friend_req.html'
    context_object_name = 'friend_reqs'

    def get_queryset(self):
        return FriendshipStatus.objects.all().filter(to_user=self.request.user, friendship_status="pending")


def accept_friend_req(request, pk):
    from_user = User.objects.all().filter(id=pk).first()
    to_user_id = request.user.id
    to_user = User.objects.all().filter(id=to_user_id).first()
    friendship_status_now = "friends"
    query = FriendshipStatus(from_user=from_user, to_user=to_user, friendship_status=friendship_status_now)
    query.save()
    query2 = FriendshipStatus(from_user=to_user, to_user=from_user, friendship_status=friendship_status_now)
    query2.save()
    qs = FriendshipStatus.objects.all().filter(from_user=from_user, to_user=to_user, friendship_status="pending")
    qs.delete()
    return redirect('music:friend-reqs')


def decline_friend_req(request, pk):
    from_user = User.objects.all().filter(id=pk).first()
    to_user = request.user
    friendship_status_now = "not_friends"
    query = FriendshipStatus(from_user=from_user, to_user=to_user, friendship_status=friendship_status_now)
    query.save()
    query2 = FriendshipStatus(from_user=to_user, to_user=from_user, friendship_status=friendship_status_now)
    query2.save()
    qs = FriendshipStatus.objects.all().filter(from_user=from_user, to_user=to_user, friendship_status="pending")
    qs.delete()
    return redirect('music:friend-reqs')


def friend_remove(request, pk):
    from_user = User.objects.all().filter(id=pk)
    to_user = request.user
    friendship_status = "not_friends"
    query = FriendshipStatus(from_user, to_user, friendship_status)
    query.save()
    query2 = FriendshipStatus(to_user, from_user, friendship_status)
    query2.save()
    qs = FriendshipStatus.objects.all().filter(from_user=from_user, to_user=request.user, friendship_status="friends")
    qs.delete()
    return redirect('music:friend-reqs')

music/templates/music/album_form.html
{% extends "music/base.html" %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a New Album</h3>
                    {% if error_message %}
                        <p><strong>{{error_message}}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form_template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Lot{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="containter-fluid">
        <div class="navbar-header"> 
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Lot</a>    
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'music:songs' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left " role="search" method="get" action="{% url 'music:songs' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if  user.username %}
                    <li class="">
                        <a href="{% url 'music:friend-reqs' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Friend Requests
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'music:list-friends' %}">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Friends
                        </a>
                    </li>
                {% endif %}
                <li class="">
                    {% if  user.username %}
                    <a href="{% url 'music:album-add' %}">
                    {% else %}
                    <a href="{% url 'music:login' %}">
                    {% endif %}
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li class="">
                    {% if  user.username %}
                        <a href="{% url 'music:logout' %}">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    {% else %}
                        <a href="{% url 'music:login' %}">
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Login
                        </a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>    
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'music:song-add' %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.song_url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'music:song-delete' song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10"> {{field}} </div>
    </div>
{% endfor %}

music/templates/music/friend_req.html
{% extends 'music/base.html' %}
{% block title %}Friend Requests{% endblock %}

{% block body %}
    {% if friend_reqs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Friendship Requests</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Username</th>
                                    <th>Email</th>
                                    <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Answer</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for friend in friend_reqs %}
                                    <tr>
                                        <td>{{ friend.from_user.username }}</td>
                                        {% if friend.from_user.email %}
                                        <td>{{ friend.from_user.email }}</td>
                                        {% else %}
                                        <td>--no email--</td>
                                        {% endif %}
                                        <td>
                                            <!--TODO: Not working, does nothing after it chages the URL-->
                                            <a href="{% url 'music:accept-friend-req' friend.from_user.id %}"
                                               class="btn btn-success btn-xs" role="button">
                                                <span class="glyphicon glyphicon-remove">&nbsp;Accept</span>
                                            </a>
                                            <a href="{% url 'music:decline-friend-req' friend.from_user.id %}"
                                               class="btn btn-danger btn-xs" role="button">
                                                <span class="glyphicon glyphicon-remove">&nbsp;Decline</span>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
            <h3>No new friend requests</h3>
    {% endif %}

</div>
{% endblock %}

music/templates/music/friends.html
{% extends 'music/base.html' %}
{% block title %}Friends{% endblock %}

{% block body %}
<div class="container container-fluid">

    <div class="row">
        {% if all_friends %}
            {% for friend in all_friends %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <div class="caption">
                            <h2>{{ user.username }}</h2>
                            <h4>{{ user.email }}</h4>
                               <a href="{% url 'music:accept-friend-req' friend.from_user.id %}"
                                  class="btn btn-danger btn-xs" role="button">
                                    <span class="glyphicon glyphicon-remove">Remove Friend</span>
                                </a>
                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <h1>You have no friends :( </h1>
        {% endif %}
    </div>
</div>
{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
        {% if  user.username %}
            <h3>{{ user.username }}'s Albums</h3>
        {% endif %}
        </div>
            {% for album in all_albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        
    </div>
</div>
{% endblock %}

music/templates/music/login_form.html
{% extends 'music/base.html' %}
{% block title %}Log In{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'music:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'music:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

music/templates/music/registration_form.html
{% extends "music/base.html" %}
{% block title %}Registration{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a New Account</h3>
                    {% if error_message %}
                        <p><strong>{{error_message}}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form_template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/song_form.html
{% extends "music/base.html" %}
{% block title %}Add Song{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add song</h3>
                    {% if error_message %}
                        <p><strong>{{error_message}}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form_template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/songs.html
{% extends 'music/base.html' %}
{% block title %}Songs{% endblock %}

{% block body %}
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.song_url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:detail' song.album.id %}">
                                                <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
            <h3>No songs available</h3>
    {% endif %}

</div>
{% endblock %}